In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
2**np.arange(1, 21)/np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
np.sum(0.1**(3*np.arange(6))*0.2**(4*np.arange(6)))

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))
np.vstack([(X[::, 0]**2 + X[::, 1]**2)**0.5, np.arctan(X[::, 1]/(X[::, 0]))]).T

array([[1.17120259, 0.62793533],
       [1.2100323 , 0.61776536],
       [0.96488405, 1.25966624],
       [0.52532249, 1.19093085],
       [0.56606686, 0.92796212]])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.random((10, 10))
np.argmax(X) // X.shape[1], np.argmax(X) % X.shape[1]



(1, 7)

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

X[np.argmin(np.linalg.norm(X - y, axis=1))]

array([0.57611498, 0.92885312])

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
np.hstack((np.arange(-3, 0, 0.1) ** 2 + 2 * np.arange(-3, 0, 0.1) + 6, np.arange(0, 2, 0.1) + 6, 
           np.arange(2, 3, 0.1) ** 2 + 4 * np.arange(2, 3, 0.1) - 4))

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
X = np.random.random((10, 10))

X - np.reshape(np.mean(X, axis=1), (-1, 1))

array([[ 0.0329655 , -0.06855091, -0.04049801,  0.28743737, -0.09631273,
        -0.38959316,  0.14851176,  0.00349791,  0.38774518, -0.26520292],
       [ 0.33151056, -0.3283731 ,  0.30012923, -0.46469902, -0.45609226,
         0.34320955,  0.25072902, -0.02560157,  0.30094105, -0.25175347],
       [ 0.07010382, -0.22378088, -0.48628484,  0.32764449,  0.32605501,
         0.24787388,  0.1021723 , -0.24477925,  0.38662377, -0.5056283 ],
       [ 0.27152109, -0.33343056,  0.20756576, -0.30579806,  0.23651443,
        -0.04831784,  0.11502101,  0.19695453, -0.57293477,  0.23290441],
       [-0.3241545 ,  0.45867348, -0.30136479, -0.26478367, -0.03559078,
        -0.29014342,  0.37003242,  0.00618136,  0.19070777,  0.19044212],
       [-0.02400225, -0.34949587, -0.22658986,  0.10541712, -0.01782206,
        -0.09473993,  0.03088703, -0.31455588,  0.49956299,  0.3913387 ],
       [ 0.19001435, -0.22124836,  0.25962929,  0.20374885,  0.25455926,
        -0.39928233, -0.3869232 ,  0.03182339

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [12]:
X = np.random.normal(loc=5, scale=2., size=1000)

print('avg =', (np.sum(X) / X.shape).item(),
'var =', (np.sum((X - (np.sum(X) / X.shape).item()) ** 2) / X.shape).item())

avg = 5.014356269758388 var = 4.090405667998091


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [13]:
np.fromfunction(lambda i, j: (i+j)%5, (5, 5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [14]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.